In [1]:
import numpy as np

#  bir numpy arrayini slicing yaptık ve alt array üzerinde yaptığımız değişiklikler ana array ıde etkiledi

In [21]:
a=np.random.randint(1,10,(5,5))
a

array([[8, 3, 3, 4, 1],
       [9, 8, 3, 7, 8],
       [5, 5, 8, 2, 5],
       [4, 1, 3, 7, 1],
       [4, 4, 7, 8, 4]])

In [22]:
sub_a=a[0:3,1:3]
sub_a

array([[3, 3],
       [8, 3],
       [5, 8]])

In [28]:
sub_a[2,1]=44444
sub_a[0,0]=11111
sub_a

array([[11111,     3],
       [    8,     3],
       [    5, 44444]])

In [29]:
a

array([[    8, 11111,     3,     4,     1],
       [    9,     8,     3,     7,     8],
       [    5,     5, 44444,     2,     5],
       [    4,     1,     3,     7,     1],
       [    4,     4,     7,     8,     4]])

## copy() metodunu kullanarak ana array ın islemlerden etkilenmesini önleriz

In [31]:
b=np.random.randint(1,10,(5,5))
b

array([[8, 8, 9, 3, 2],
       [2, 4, 3, 9, 1],
       [5, 4, 5, 7, 4],
       [4, 7, 2, 7, 7],
       [1, 9, 6, 2, 9]])

In [33]:
sub_b=b[0:3,1:3].copy()
sub_b

array([[8, 9],
       [4, 3],
       [4, 5]])

In [34]:
sub_b[0,1]=9999
sub_b[1,0]=8888
sub_b

array([[   8, 9999],
       [8888,    3],
       [   4,    5]])

In [36]:
sub_b=sub_b*3
sub_b

array([[   24, 29997],
       [26664,     9],
       [   12,    15]])

In [37]:
b

array([[8, 8, 9, 3, 2],
       [2, 4, 3, 9, 1],
       [5, 4, 5, 7, 4],
       [4, 7, 2, 7, 7],
       [1, 9, 6, 2, 9]])

### ana array görüldüğü gibi değişikliklerden etkilenmedi ilk halini aldı