In [1]:
import numpy as np

In [2]:
a=np.arange(1,30,3)
a

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [6]:
istenen=[1,3,5]
a[istenen]

array([ 4, 10, 16])

### çok boyutlu array da fancy index uygulaması

In [7]:
b=np.random.randint(1,45,(3,5))
b

array([[ 7, 21, 14, 20, 38],
       [12, 14, 22,  3, 13],
       [42,  3, 24, 30, 12]])

In [18]:
satir=np.array([1,2])
sutun=np.array([1,4])
b[satir,sutun]

array([14, 12])

In [25]:
k=np.arange(0,9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

####  k[:,[1,2]] (fancy index) ile k[:,1:3] (normal index leme) aynı anlama gelir

In [27]:
k[:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [28]:
k[:,1:3]

array([[1, 2],
       [4, 5],
       [7, 8]])