In [1]:
import numpy as np

In [3]:
a=np.random.randint(5,42,8)
a

array([40, 35, 18, 12, 35, 34,  8, 20])

In [10]:
(a%2==0) & (a<=20)

array([False, False,  True,  True, False, False,  True,  True])

In [6]:
kosul=(a%2==0) & (a<=20)
a[kosul]

array([18, 12,  8, 20])

In [8]:
a[(a%2==0) & (a>=20)]

array([40, 34, 20])

In [11]:
b=np.arange(20).reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
b[b%5==0]

array([ 0,  5, 10, 15])

In [13]:
b[b<9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])