In [1]:
import numpy as np

* identity matris olusturma

In [2]:
a=np.eye(3,5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [3]:
b=np.eye(2,2)
b

array([[1., 0.],
       [0., 1.]])

In [5]:
c=np.ones((2,3,4))
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

_size metodu eleman syısını döndürür_

In [9]:
c.size

24

In [10]:
d=np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
d.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### -1 ile size lardan biri belli ise diğerini kendi ayarlar

In [12]:
d.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
d.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### newaxis ile boyut ekleme yapılır newaxis yerine None da yazılabilir

In [15]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
d[np.newaxis,:]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
d[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [17]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
d[None,:]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
d[:,None]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [24]:
e=np.arange(20).reshape(5,4) 
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
np.vsplit(e,[2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [29]:
f=np.arange(1,13).reshape(3,4)
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
g=np.arange(1,13).reshape(3,4)
g

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
h=g[1,[1,3]] 
h

array([6, 8])

In [37]:
k=np.arange(1,21).reshape(4,5) 
k

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [39]:
np.sum(k,axis=0).shape

(5,)

In [40]:
np.all(k>8,axis=1)

array([False, False,  True,  True])

In [42]:
np.any(k>3,axis=1)

array([ True,  True,  True,  True])