In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a=[1,2,3]
ax=np.array(a)
ax

array([1, 2, 3])

In [7]:
type(ax)

numpy.ndarray

In [9]:
np.array([1.23,3,4,5],dtype=int)

array([1, 3, 4, 5])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [17]:
np.arange(0,25,4)

array([ 0,  4,  8, 12, 16, 20, 24])

In [19]:
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [23]:
np.random.normal(10,4,(2,3))

array([[ 7.02788791, 10.15360422,  5.73534367],
       [ 6.51408497,  2.68422054, 15.17831543]])

In [24]:
np.random.randint(3,8,(4,5))

array([[6, 4, 3, 6, 4],
       [4, 5, 6, 7, 5],
       [5, 4, 6, 5, 5],
       [4, 3, 6, 4, 7]])