In [1]:
import numpy as np

In [8]:
a=np.random.randn(8).reshape((4,2))
a

array([[ 1.221645  , -0.17108918],
       [ 1.30087119, -0.02304111],
       [ 1.16777639,  0.1251499 ],
       [-0.06014399,  0.22209977]])

In [9]:
a.reshape((2,4))
a

array([[ 1.221645  , -0.17108918],
       [ 1.30087119, -0.02304111],
       [ 1.16777639,  0.1251499 ],
       [-0.06014399,  0.22209977]])

In [12]:
b=np.random.randint(10,size=10)
b

array([8, 8, 1, 7, 3, 3, 6, 6, 0, 2])

In [16]:
c=b.reshape((1,10))
c

array([[8, 8, 1, 7, 3, 3, 6, 6, 0, 2]])

In [17]:
c.ndim

2

In [18]:
c.shape

(1, 10)