In [1]:
import numpy as np

In [5]:
a=np.random.randint(1,10,4)
a

array([3, 3, 2, 4])

In [6]:
b=np.random.randint(1,10,4)
b

array([4, 1, 7, 8])

In [8]:
c=np.concatenate([a,b])
c

array([3, 3, 2, 4, 4, 1, 7, 8])

In [17]:
x=np.random.randn(4,2)
x

array([[-1.05996135,  0.39707512],
       [ 0.04792697, -0.10637233],
       [-0.16715688,  1.12118081],
       [ 2.10481014,  0.84504608]])

In [22]:
y=np.random.randint(1,10,(4,2))
y

array([[6, 9],
       [5, 1],
       [5, 5],
       [5, 4]])

In [23]:
z=np.concatenate([x,y])
z

array([[-1.05996135,  0.39707512],
       [ 0.04792697, -0.10637233],
       [-0.16715688,  1.12118081],
       [ 2.10481014,  0.84504608],
       [ 6.        ,  9.        ],
       [ 5.        ,  1.        ],
       [ 5.        ,  5.        ],
       [ 5.        ,  4.        ]])

In [28]:
k=np.concatenate([x,y],axis=1)
k

array([[-1.05996135,  0.39707512,  6.        ,  9.        ],
       [ 0.04792697, -0.10637233,  5.        ,  1.        ],
       [-0.16715688,  1.12118081,  5.        ,  5.        ],
       [ 2.10481014,  0.84504608,  5.        ,  4.        ]])

In [27]:
w=z.reshape((4,4))
w

array([[-1.05996135,  0.39707512,  0.04792697, -0.10637233],
       [-0.16715688,  1.12118081,  2.10481014,  0.84504608],
       [ 6.        ,  9.        ,  5.        ,  1.        ],
       [ 5.        ,  5.        ,  5.        ,  4.        ]])