_split işlemini yaparken indekslere göre yapıyoruz_

In [1]:
import numpy as np

In [3]:
a=np.arange(1,50,8)
a

array([ 1,  9, 17, 25, 33, 41, 49])

In [7]:
x,y,z=np.split(a,[3,5])
x

array([ 1,  9, 17])

In [8]:
y

array([25, 33])

In [9]:
z

array([41, 49])

_iki boyutlu arrayları split etme_

* satırlardan bölmek için vsplit
* sütünlardan bölmek için hsplit kullanılır.

In [13]:
marr=np.random.randint(1,50,(4,4))
marr

array([[20, 18, 18, 41],
       [43, 44, 35,  8],
       [ 3, 20, 13, 44],
       [17, 20,  6, 24]])

In [16]:
a,b=np.vsplit(marr,[2])
a

array([[20, 18, 18, 41],
       [43, 44, 35,  8]])

In [17]:
b

array([[ 3, 20, 13, 44],
       [17, 20,  6, 24]])

In [19]:
c,d=np.hsplit(marr,[1])
c

array([[20],
       [43],
       [ 3],
       [17]])

In [20]:
d

array([[18, 18, 41],
       [44, 35,  8],
       [20, 13, 44],
       [20,  6, 24]])