In [1]:
import numpy as np

In [4]:
a=np.random.randint(9,85,12)
a

array([10, 65, 77, 13, 56, 47, 19, 46, 57, 78, 51, 36])

In [5]:
np.sort(a)

array([10, 13, 19, 36, 46, 47, 51, 56, 57, 65, 77, 78])

In [13]:
marr=np.random.normal(5,12,(5,4))
marr

array([[ 10.45143875,  13.66702854,  21.11412224, -34.26544787],
       [  6.32475516,   3.14555696,  -1.32233167, -15.97212612],
       [  1.26382284,  22.51496729,  -6.4658647 ,  12.35020235],
       [ 11.7239972 ,  28.17401677, -10.35357385,   2.28466166],
       [ 13.79954197,  14.38057335,  20.2703264 ,   1.40612514]])

In [17]:
np.sort(marr)

array([[-34.26544787,  10.45143875,  13.66702854,  21.11412224],
       [-15.97212612,  -1.32233167,   3.14555696,   6.32475516],
       [ -6.4658647 ,   1.26382284,  12.35020235,  22.51496729],
       [-10.35357385,   2.28466166,  11.7239972 ,  28.17401677],
       [  1.40612514,  13.79954197,  14.38057335,  20.2703264 ]])

* _axis=1 dediğimizde her satır kendi içinde sıralanır (sort metodunun default değeridir)_
* _axis=0 dediğimizde de her sütun kendi içerisinde sıralanır

In [16]:
np.sort(marr,axis=0)

array([[  1.26382284,   3.14555696, -10.35357385, -34.26544787],
       [  6.32475516,  13.66702854,  -6.4658647 , -15.97212612],
       [ 10.45143875,  14.38057335,  -1.32233167,   1.40612514],
       [ 11.7239972 ,  22.51496729,  20.2703264 ,   2.28466166],
       [ 13.79954197,  28.17401677,  21.11412224,  12.35020235]])