In [3]:
import numpy as np

_tek boyutlu arrayler de slicing_

In [7]:
a=np.random.randint(10,45,8)
a

array([37, 24, 12, 11, 12, 23, 40, 30])

In [8]:
a[0:5]

array([37, 24, 12, 11, 12])

In [9]:
a[4:]

array([12, 23, 40, 30])

In [10]:
a[1::3]

array([24, 12, 30])

_çok boyutlu arraylarde slicing işlemi_

In [11]:
b=np.random.randint(12,54,(4,5))
b

array([[33, 25, 27, 46, 20],
       [39, 32, 26, 19, 33],
       [30, 17, 46, 48, 33],
       [51, 37, 40, 21, 53]])

In [13]:
b[0:3,2:4]

array([[27, 46],
       [26, 19],
       [46, 48]])

In [14]:
b[:,0:3]

array([[33, 25, 27],
       [39, 32, 26],
       [30, 17, 46],
       [51, 37, 40]])

In [18]:
b[0,:]

array([33, 25, 27, 46, 20])

In [19]:
b[:,0]

array([33, 39, 30, 51])