In [1]:
import numpy as np
import pandas as pd

In [6]:
a=np.arange(4,13)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
af=pd.DataFrame(a,columns=["items"])
af

items
0      4
1      5
2      6
3      7
4      8
5      9
6     10
7     11
8     12

In [14]:
b=np.random.randint(5,19,(3,3))
b

array([[ 6,  9, 17],
       [14,  6, 12],
       [ 7,  8, 16]])

In [18]:
bf=pd.DataFrame( b, columns=["boyut1","boyut2","boyut3"])
bf

boyut1  boyut2  boyut3
0       6       9      17
1      14       6      12
2       7       8      16

In [19]:
bf.columns=("var1","var2","var3")
bf

var1  var2  var3
0     6     9    17
1    14     6    12
2     7     8    16

In [21]:
bf.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['var1', 'var2', 'var3'], dtype='object')]

In [22]:
bf.shape

(3, 3)

In [23]:
bf.ndim

2

In [24]:
bf.size

9

In [27]:
bf.values

array([[ 6,  9, 17],
       [14,  6, 12],
       [ 7,  8, 16]])

In [28]:
bf.index

RangeIndex(start=0, stop=3, step=1)

In [32]:
bf.keys()

Index(['var1', 'var2', 'var3'], dtype='object')

In [33]:
bf.head(2)

var1  var2  var3
0     6     9    17
1    14     6    12

In [36]:
bf.tail(2)

var1  var2  var3
1    14     6    12
2     7     8    16