In [1]:
import seaborn as sns
import missingno as msno
import pandas as pd
import numpy as np
df = sns.load_dataset('titanic')
df = df.select_dtypes(include = ['float64', 'int64'])
print(df.head())
df.isnull().sum()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500


survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [2]:
!pip install ycimpute

In [3]:
var_names = list(df)
var_names

['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare']

In [4]:
n_df = np.array(df)
n_df[:10]

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       [ 1.    ,  1.    , 35.    ,  1.    ,  0.    , 53.1   ],
       [ 0.    ,  3.    , 35.    ,  0.    ,  0.    ,  8.05  ],
       [ 0.    ,  3.    ,     nan,  0.    ,  0.    ,  8.4583],
       [ 0.    ,  1.    , 54.    ,  0.    ,  0.    , 51.8625],
       [ 0.    ,  3.    ,  2.    ,  3.    ,  1.    , 21.075 ],
       [ 1.    ,  3.    , 27.    ,  0.    ,  2.    , 11.1333],
       [ 1.    ,  2.    , 14.    ,  1.    ,  0.    , 30.0708]])

In [5]:
from ycimpute.imputer import iterforest
dff = iterforest.IterImput().complete(n_df)

In [6]:
dff = pd.DataFrame(dff, columns = var_names)

In [7]:
dff.head(10)

survived  pclass    age  sibsp  parch     fare
0       0.0     3.0  22.00    1.0    0.0   7.2500
1       1.0     1.0  38.00    1.0    0.0  71.2833
2       1.0     3.0  26.00    0.0    0.0   7.9250
3       1.0     1.0  35.00    1.0    0.0  53.1000
4       0.0     3.0  35.00    0.0    0.0   8.0500
5       0.0     3.0  23.46    0.0    0.0   8.4583
6       0.0     1.0  54.00    0.0    0.0  51.8625
7       0.0     3.0   2.00    3.0    1.0  21.0750
8       1.0     3.0  27.00    0.0    2.0  11.1333
9       1.0     2.0  14.00    1.0    0.0  30.0708

In [10]:
dff.isnull().sum()

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64

In [12]:
import seaborn as sns
import missingno as msno
import pandas as pd
import numpy as np
df = sns.load_dataset('titanic')
df = df.select_dtypes(include = ['float64', 'int64'])
print(df.head())
df.isnull().sum()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500


survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [13]:
from ycimpute.imputer import EM

In [14]:
var_names=list(df)
var_names

['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare']

In [16]:
n_df=np.array(df)
n_df[:10]

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       [ 1.    ,  1.    , 35.    ,  1.    ,  0.    , 53.1   ],
       [ 0.    ,  3.    , 35.    ,  0.    ,  0.    ,  8.05  ],
       [ 0.    ,  3.    ,     nan,  0.    ,  0.    ,  8.4583],
       [ 0.    ,  1.    , 54.    ,  0.    ,  0.    , 51.8625],
       [ 0.    ,  3.    ,  2.    ,  3.    ,  1.    , 21.075 ],
       [ 1.    ,  3.    , 27.    ,  0.    ,  2.    , 11.1333],
       [ 1.    ,  2.    , 14.    ,  1.    ,  0.    , 30.0708]])

In [21]:
dff=EM().complete(n_df)
dff

array([[ 0.        ,  3.        , 22.        ,  1.        ,  0.        ,
         7.25      ],
       [ 1.        ,  1.        , 38.        ,  1.        ,  0.        ,
        71.2833    ],
       [ 1.        ,  3.        , 26.        ,  0.        ,  0.        ,
         7.925     ],
       ...,
       [ 0.        ,  3.        , 23.30151219,  1.        ,  2.        ,
        23.45      ],
       [ 1.        ,  1.        , 26.        ,  0.        ,  0.        ,
        30.        ],
       [ 0.        ,  3.        , 32.        ,  0.        ,  0.        ,
         7.75      ]])

In [22]:
dff=pd.DataFrame(dff,columns=var_names)
dff.head(15)

survived  pclass        age  sibsp  parch     fare
0        0.0     3.0  22.000000    1.0    0.0   7.2500
1        1.0     1.0  38.000000    1.0    0.0  71.2833
2        1.0     3.0  26.000000    0.0    0.0   7.9250
3        1.0     1.0  35.000000    1.0    0.0  53.1000
4        0.0     3.0  35.000000    0.0    0.0   8.0500
5        0.0     3.0  29.103364    0.0    0.0   8.4583
6        0.0     1.0  54.000000    0.0    0.0  51.8625
7        0.0     3.0   2.000000    3.0    1.0  21.0750
8        1.0     3.0  27.000000    0.0    2.0  11.1333
9        1.0     2.0  14.000000    1.0    0.0  30.0708
10       1.0     3.0   4.000000    1.0    1.0  16.7000
11       1.0     1.0  58.000000    0.0    0.0  26.5500
12       0.0     3.0  20.000000    0.0    0.0   8.0500
13       0.0     3.0  39.000000    1.0    5.0  31.2750
14       0.0     3.0  14.000000    0.0    0.0   7.8542